### ISSUE TITLE
Compatibility with PostCSS 8

### ISSUE THREAD

**Issue by jonnitto** [madeleineostoja/postcss-hexrgba#31]
**Thanks for your PostCSS plugin!** 

As you probably know, [PostCSS 8] was released a few days ago. It would be great if you could make this plugin compatible with the latest version. The creators of the project have even released this [migration guide].

[PostCSS 8]: https://github.com/postcss/postcss/releases/tag/8.0.0
[migration guide]: https://evilmartians.com/chronicles/postcss-8-plugin-migration

**Comment by alexander-schranz** [comment]
I'm also running into an issue with postcss 8 seems not to work. @jonnitto did you find a workaround to get it work with it?

**Comment by alexander-schranz** [comment]
#33 was merged and released as 2.1.0 so this is know fixed :)
